#+startup: num

* ツールの説明と設定

** AeroSpace

- https://github.com/nikitabobko/AeroSpace
- https://nikitabobko.github.io/AeroSpace/guide

i3 ライクな Window Manager

*** Mission Control のサムネイルが小さくなる問題

Mission Control を起動するとアプリのサムネイルがとても小さく表示される不具合があります。

次のコマンドを打つと解決します。

#+begin_src
  defaults write com.apple.spaces spans-displays -bool true && killall SystemUIServer
#+end_src

** Bat

better =cat=

*** Theme

- [[https://github.com/catppuccin/bat][catppuccin/bat: 🦇️ Soothing pastel theme for Bat]]

Theme には Catppuccin Frappe を使用しています。

初回のみキャッシュをリビルドしましょう。

#+begin_src
  bat cache --build
#+end_src

** DeskPad

- GitHub: https://github.com/Stengo/DeskPad

画面共有用に仮想ディスプレイ (Virtual Display) を作るアプリ

** Emacs

#+begin_src emacs-lisp
(emacs-version)
#+end_src

#+RESULTS:
: GNU Emacs 31.0.50 (build 1, aarch64-apple-darwin23.6.0, NS appkit-2487.70 Version 14.6.1 (Build 23G93))
:  of 2024-08-09

see https://github.com/ataka/emacs-d.git

** Eza

Better =ls=

#+begin_src
  brew install eza
#+end_src

** [[https://github.com/fastfetch-cli/fastfetch][Fastfetch]]

システム情報取得ツール。Neofetch の後継。

** Fontforge

フォントを編集するアプリ。

ARM 用のアプリは提供されていない?
`brew` でインストールすると、次の警告が出ます。

#+begin_src
  ==> Caveats
  fontforge is built for Intel macOS and so requires Rosetta 2 to be installed.
  You can install Rosetta 2 with:
    softwareupdate --install-rosetta --agree-to-license
  Note that it is very difficult to remove Rosetta 2 once it is installed.
#+end_src

幸い手元の環境は既に Rosetta 2 だったのでそのままスルーします。

** fzf

=zoxide= との連携で力を発揮する Fazzy Finder

#+begin_src
  brew install fzf
#+end_src

** [[https://github.com/ghostty-org/ghostty][Ghostty]]

=ZIG= 言語で書かれたターミナル

*** インストール後の権限

#+begin_quote
Warning: Your terminal does not have App Management permissions, so Homebrew will delete and reinstall the app.
This may result in some configurations (like notification settings or location in the Dock/Launchpad) being lost.
To fix this, go to System Settings > Privacy & Security > App Management and add or enable your terminal.
#+end_quote

** Git

- =.gitconfig=

** GitHub Copilot

*** GitHub Copilot for Xcode

**** 初期設定

1. GitHub Copilot for Xcode を開く
2. アクセシビリティ機能へのアクセス許可を与える
   - 「システム設定 > プライバシーとセキュリティ > アクセシビリティ」から =GitHub Copilot for Xcode Extension= を許可する
3. 歯車マークをクリックして、設定画面を開く
   - 「システム設定 > ログイン項目と機能拡張」から =Xcode Source Editor= で =GitHub Copilot for Xcode Extension= を許可する
4. GitHub Copilot for Xcode に戻り、サインインする
   - GitHub への Activation 画面が開くので、その通り実行する

**** 使い方

- =TAB= 提案されたコードを受け入れる
- =Option= 複数行の提案を表示する

**** 自前のキーカスタマイズ

- =Ctrl + [= Previous Suggestion
- =Ctrl + ]= Next Suggestion
- =Ctrl + {= Open chat in GitHub Copilot for Xcode

*** GitHub Copilot for Emacs

see README.org in =.emacs.d=

*** GitHub Copilot for VSCode

1. 画面左のサイドバーから「拡張機能」をクリック
2. 「GitHub Copilot」 (と欲しければ「GitHub Copilot Chat」) をインストール
3. 画面右下の GitHub アイコンから「Sign in to use Copilot」を実行

** Gnuplot

- http://www.gnuplot.info/

ポータブルなグラフ描画ツール

** [[https://www.homerow.app/][HomeRow]]

Clickable な要素にキーボードショートカットを用意するツール。

Homebrew 版は用意されていません。

** [[https://imagemagick.org/index.php][ImageMagick]]

多採な画像操作ツール

** JankyBorders

- https://github.com/FelixKratz/JankyBorders

ウィンドウ枠に色を付けるツール。

コマンド名は =borders=

** Just

- https://github.com/casey/just

コマンドランナー。

*** 補完機能の追加

- https://github.com/casey/just/issues/223

=~/.zsh/completion/_just= に次のファイルを置きます。

#+begin_src shell
  #compdef _just just
  #autoload

  _just () {
      local -a subcmds

      subcmds=($(just --summary))

      _describe 'command' subcmds
  }

  _just "$@"
#+end_src

** Karabiner Elements

KMonad と相性が悪いので Makefile からインストール・スクリプトを消します。

*** Install

インストールする場合は下記コマンドを実行します。

#+begin_src
  brew install --cask karabiner-elements
#+end_src

*** Dvorak Layout

#+begin_src
  '   ,   .   p   y      f   g   c   r   l
  a   o   e   u   i      d   h   t   n   s
  ;   q   j   k   x      b   m   w   v   z
#+end_src

*** Home Row Mods

Home Row Mods の設定は https://github.com/Leo-keeb/Karabiner-Elements-Advanced-Settings を参考にしました。

#+begin_src
  '   ,   .   p   y      f   g   c   r   l
  Cmd Sft Opt Ctl i      d   Ctl Opt Sft Cmd
  ;   q   j   k   x      b   m   w   v   z
#+end_src

** KMonad

- [[https://tgc54.com/en/post/kmonad-macos/?__readwiseLocation=][Setting up KMonad on macOS]]

*** インストール

Karabiner-Elements が入っているなら、事前に Karabiner-Elements をアンインストールしておきます。

#+begin_src
  brew uninstall --cask karabiner-elements
#+end_src

必要なパッケージをインストールします。

#+begin_src
  make install-kmonad
#+end_src

KMonad を取得します。

#+begin_src 
  cd ~/project

  git clone --recursive https://github.com/kmonad/kmonad.git
  cd kmonad
#+end_src

Karabiner-DriverKit-VirtualHIDDevice をインストール (対話的) します

#+begin_src
  open c_src/mac/Karabiner-DriverKit-VirtualHIDDevice/dist/Karabiner-DriverKit-VirtualHIDDevice-5.0.0.pkg
#+end_src

Karabiner-DriverKit-VirtualHIDDevice をインストール後に Activate (対話的) します

#+begin_src
  /Applications/.Karabiner-VirtualHIDDevice-Manager.app/Contents/MacOS/Karabiner-VirtualHIDDevice-Manager activate
#+end_src

「設定 > 一般 > ログイン項目と機能拡張 > 機能拡張 > ドライバ機能拡張」から =org.pqrs.Karabiner-DriverKit-VirtualHIDDevice= をオンにします。

Daemon を起動します。

#+begin_src
sudo '/Library/Application Support/org.pqrs/Karabiner-DriverKit-VirtualHIDDevice/Applications/Karabiner-VirtualHIDDevice-Daemon.app/Contents/MacOS/Karabiner-VirtualHIDDevice-Daemon'
#+end_src

Daemon 起動は kmonad 実行前に必須?

ビルドして ~/.local/bin にインストールします。

#+begin_src
  stack install --flag kmonad:dext
#+end_src

Catalina (10.15) からキーイベントのキャプチャーにはシステム設定でパーミッションを与える必要があります。
「設定 > プライバシーとセキュリティ > プライバシー > 入力監視」から KMonad を実行するアプリ (=~/.local/bin/kmonad=) を追加します。

Finder で隠しフォルダーを表示するには =Command + Shift + .= を使います。

*** KMonad を実行する

=sudo= を使って起動します

#+begin_src
  sudo ~/.local/bin/kmonad ~/project/dotfiles/kmonad/foo.kbd
#+end_src

*** 起動時に KMonad を実行する

#+begin_src plist
  <?xml version="1.0" encoding="utf-8"?>
  <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
  <plist version="1.0">
    <dict>
      <key>Label</key>
      <string>local.kmonad</string>
      <key>Program</key>
      <string>/Users/[user]/.local/bin/kmonad</string>
      <key>ProgramArguments</key>
      <array>
        <string>/Users/[user]/.local/bin/kmonad</string>
        <string>/Users/[user]/.config/config.kbd</string>
      </array>
      <key>RunAtLoad</key>
      <true />
      <key>StandardOutPath</key>
      <string>/tmp/kmonad.stdout</string>
      <key>StandardErrorPath</key>
      <string>/tmp/kmonad.stderr</string>
    </dict>
  </plist>
#+end_src

*** 起動時に DText Daemon を実行する

#+begin_src plist
  <?xml version="1.0" encoding="UTF-8"?>
  <!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
  <plist version="1.0">
    <dict>
      <key>Label</key>
      <string>org.pqrs.service.daemon.Karabiner-VirtualHIDDevice-Daemon</string>
      <key>KeepAlive</key>
      <true/>
      <key>ProcessType</key>
      <string>Interactive</string>
      <key>ProgramArguments</key>
      <array>
        <string>/Library/Application Support/org.pqrs/Karabiner-DriverKit-VirtualHIDDevice/Applications/Karabiner-VirtualHIDDevice-Daemon.app/Contents/MacOS/Karabiner-VirtualHIDDevice-Daemon</string>
      </array>
    </dict>
  </plist>
#+end_src

*** KMonad を適用するキーボードを限定する

#+begin_src
  (defcfg
    input  (iokit-name "キーボードのデバイス名")
    output (kext)
    fallthrough true
  )
#+end_src

キーボードのデバイス名は =list-keyboards= コマンドで取得できます。

#+begin_src
  ❯ ./list-keyboards
  Apple Internal Keyboard / Trackpad
  Karabiner DriverKit VirtualHIDKeyboard 1.8.0
#+end_src

=list-keyboards= コマンドは kmonad リポジトリー内で作成します。

#+begin_src
  cd ~/project/kmonad
  cd c_src/mac
  make
#+end_src

*** 作成した kbd ファイル

| ファイル名                               | 対象キーボード            | Layout | IM | メモ              |
|------------------------------------------+---------------------------+--------+----+-------------------|
| なし                                     | Kinesis Advantage 360 Pro | Dvorak | Qw |                   |
| =home-row-mods=                          | Kinesis Advantage 2       | Dvorak | Qw |                   |
| =home-row-mods-qwerty=                   | Internal Keyboard         | Qwerty | Dv | 基本利用しない    |
| =home-row-mods-qwerty-apple=             | Internal Keyboard         | Qwerty | Qw |                   |
| =home-row-mods-qwerty-apple-space-cadet= | Internal Keyboard         | Qwerty | Qw | Hyper, Super 対応 |

** MacTcode

https://github.com/mad-p/MacTcode/

*** アップデート

1. dmg ファイルをダウンロード & 展開する
2. 古いディレクトリーを削除して、新しいものをコピーする
3. ログインし直す

#+begin_src
  cd /Library/Input\ Methods
  sudo rm -rf MacTcode.app
  cd ~/Downloads
  sudo cp -r MacTcode.app /Library/Input\ Methods/
#+end_src

** GNU Screen

- =.screenrc=

** Serie

Rust 製の git graph ツール

** SketchyBar

Better メニューバー

*** デフォルトのメニューバーを隠す

完全にメニューバーを非表示にする方法はないので、自動表示を「常に」に設定します。

- 設定アプリ > コントロールセンター > 「メニューバーを自動的に表示/非表示」 > 常に

*** SkeychyBar の起動

#+begin_src
  brew services start sketchybar
#+end_src

** oh my posh

*** oh my posh のインストール

#+begin_src
  brew install jandedobbeleer/oh-my-posh/oh-my-posh
#+end_src

** Vivaldi

*** Quick Command

1. 「現在のタブでリンクを開く」を選択する
2. コマンドパラメーターに Bookmarklet 相当の JavaScript を貼り付ける

**** Copy URL

#+begin_src javacript
  javascript:(function(){e = document.createElement('textarea');e.textContent = document.URL;document.body.appendChild(e);e.select();document.execCommand('copy');e.remove();})();if(history.replaceState){history.replaceState({},null,location.href);};
#+end_src

**** Copy as Markdown

#+begin_src javacript
  javascript:(function(){e = document.createElement('textarea');e.textContent = '['+document.title +']('+ document.URL+')';document.body.appendChild(e);e.select();document.execCommand('copy');e.remove();})();if(history.replaceState){history.replaceState({},null,location.href);};
#+end_src

**** Copy as Plain Text

#+begin_src javacript
  javascript:(function(){e = document.createElement('textarea');e.textContent = '- '+document.title +'\n'+ document.URL;document.body.appendChild(e);e.select();document.execCommand('copy');e.remove();})();if(history.replaceState){history.replaceState({},null,location.href);};
#+end_src

**** Copy as Org

#+begin_src javacript
  javascript:(function(){e = document.createElement('textarea');e.textContent = '[['+document.URL +']['+ document.title+']]';document.body.appendChild(e);e.select();document.execCommand('copy');e.remove();})();if(history.replaceState){history.replaceState({},null,location.href);};
#+end_src

** WezTerm

*** WezTerm のインストール

#+begin_src
  brew install --cask wezterm
#+end_src

*** WezTerm の使い方

- =Cmd + T= タブを新しく作る
- =Cmd + W= タブを閉じる

*** Theme

Catppuccin Frappe テーマを使用しています。

Wezterm はシステムのライト/ダークテーマの切替に対応していますが、その機能を利用していません。
Wezterm 上で使う CUI ツールが対応していないためです。

** zoxide

Better =cd=

#+begin_src
  brew install zoxide
#+end_src

** zsh

- =.zshrc=
- =.zprofile=

*** zsh (homebrew 版)

#+begin_src
  brew install zsh
#+end_src

**** zsh (homebrew 版) の設定

=/etc/shells= に次の行を追加します。

#+begin_src
  /opt/homebrew/bin/zsh
#+end_src

その後、ログイン・シェルの変更を実施します。

#+begin_src
  chsh -s /opt/homebrew/bin/zsh
#+end_src

* プログラミング言語の設定

** Mermaid

*** mmdc

Mermaid のソースコードから画像等を作成するコマンドラインツール。

**** mmdc のインストール

#+begin_src 
npm install -g @mermaid-js/mermaid-cli
#+end_src

**** Rakefile のサンプル

次の Rakefile を用意しておくと、ビルドが楽になります。

#+begin_src ruby
  # frozen_string_literal: true

  task :default => :uml

  desc "UML 図を更新する"
  task :uml => %w[
    foo.png
  ]

  rule '.png' => '.mmdc' do |t|
    sh "mmdc --input #{t.source} --output #{t.name} --scale 4"
  end

  rule '.svg' => '.mmdc' do |t|
    sh "mmdc --input #{t.source} --output #{t.name}"
  end
#+end_src

** PlantUML

*** plantuml

PlantUML のソースコードから画像等を作成するコマンドラインツール。

**** plantuml のインストール

#+begin_src 
brew install plantuml
#+end_src

**** Rakefile のサンプル

次の Rakefile を用意しておくと、ビルドが楽になります。

#+begin_src ruby
  # frozen_string_literal: true

  PLANTUML = "/opt/homebrew/bin/plantuml"

  task :default => :uml

  desc "UML 図を更新する"
  task :uml => %w[
    foo.png
  ]

  rule '.png' => '.plantuml' do |t|
    sh "#{PLANTUML} -Pteoz=true #{t.source}"
  end

  rule '-simple.plantuml' => '.plantuml' do |t|
    sh "sed -e \"s/' hide members/hide members/g\" #{t.source} > #{t.name}"
  end
#+end_src

* フォントの設定

** UDEV Gothic

- https://github.com/yuru7/udev-gothic

BIZ UDGothic と JetBrains Mono を組み合わせたフォント。

JetBrains Mono は Ligature に対応しています。

Nerd Fonts に対応した =UDEVGothic_NF_v2.0.0.zip= をダウンロードしています。

** Victor Mono

- https://rubjo.github.io/victor-mono/

Ligature に対応した英文フォント。

* Theme

** ANSI Escape Sequences

- Text Attributes
  - 0 : All attributes off
  - 1 : Bold on
  - 2 : Dim/Faint on
  - 3 : Italic on
  - 4 : Underscore
  - 5 : Blink on
  - 6 : Hidden on
  - 7 : Reverse video on
  - 8 : Concealed on
  - 9 : Strikethrough on

| Color Name     | Foreground Color | Background Color |
|----------------+------------------+------------------|
| Black          | 30               | 40               |
| Red            | 31               | 41               |
| Green          | 32               | 42               |
| Yellow         | 33               | 43               |
| Blue           | 34               | 44               |
| Magenta        | 35               | 45               |
| Cyan           | 36               | 46               |
| White          | 37               | 47               |
| Bright Black   | 90               | 100              |
| Bright Red     | 91               | 101              |
| Bright Green   | 92               | 102              |
| Bright Yellow  | 99               | 109              |
| Bright Blue    | 94               | 104              |
| Bright Magenta | 95               | 105              |
| Bright Cyan    | 96               | 106              |
| Bright White   | 97               | 107              |

** Catppuccine

*** Frappe

| Color Name | ANSI    | Bright  | ANSI Name | Bright Name |
|------------+---------+---------+-----------+-------------+
| Black      | #51576d | #626880 | surface1  | surface2    |
| Red        | #e78284 | #e78284 | red       | red         |
| Green      | #a6d189 | #a6d189 | green     | green       |
| Yellow     | #e5c890 | #e5c890 | yellow    | yellow      |
| Blue       | #8caaee | #8caaee | blue      | blue        |
| Magenta    | #f4b8e4 | #f4b8e4 | pink      | pink        |
| Cyan       | #81c8be | #81c8be | teal      | teal        |
| White      | #b5bfe2 | #a5adce | subtext1  | subtext0    |

* マイブログ

** Prism.js

JavaScript

#+begin_src xml
  <script src="https://cdn.jsdelivr.net/combine/npm/prismjs@1/components/prism-core.min.js,npm/prismjs@1/components/prism-bash.min.js,npm/prismjs@1/components/prism-css.min.js,npm/prismjs@1/components/prism-diff.min.js,npm/prismjs@1/components/prism-git.min.js,npm/prismjs@1/components/prism-javascript.min.js,npm/prismjs@1/components/prism-json.min.js,npm/prismjs@1/components/prism-jsonp.min.js,npm/prismjs@1/components/prism-lisp.min.js,npm/prismjs@1/components/prism-markdown.min.js,npm/prismjs@1/components/prism-mermaid.min.js,npm/prismjs@1/components/prism-ruby.min.js,npm/prismjs@1/components/prism-shell-session.min.js,npm/prismjs@1/components/prism-sql.min.js,npm/prismjs@1/components/prism-swift.min.js,npm/prismjs@1/components/prism-toml.min.js,npm/prismjs@1/components/prism-xml-doc.min.js,npm/prismjs@1/components/prism-yaml.min.js,npm/prismjs@1/components/prism-lua.min.js,npm/prismjs@1,npm/prismjs@1/plugins/line-numbers/prism-line-numbers.min.js,npm/prismjs@1/plugins/line-highlight/prism-line-highlight.min.js,npm/prismjs@1/plugins/toolbar/prism-toolbar.min.js,npm/prismjs@1/plugins/show-language/prism-show-language.min.js,npm/prismjs@1/plugins/copy-to-clipboard/prism-copy-to-clipboard.min.js,npm/prismjs@1/plugins/treeview/prism-treeview.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/prismjs@1/plugins/autoloader/prism-autoloader.min.js"></script>
#+end_src

CSS

#+begin_src xml
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/combine/npm/prismjs@1/themes/prism.min.css,npm/prismjs@1/plugins/line-numbers/prism-line-numbers.min.css,npm/prismjs@1/plugins/line-highlight/prism-line-highlight.min.css,npm/prismjs@1/plugins/toolbar/prism-toolbar.min.css,npm/prismjs@1/plugins/treeview/prism-treeview.min.css"/>
#+end_src

* 同僚etc.が使っているアプリ

** [[https://code.visualstudio.com/][Visual Studio Code]]

Microsoft が開発しているマルチプラットフォームな IDE
