
* ツールの説明と設定

** AeroSpace

- https://github.com/nikitabobko/AeroSpace
- https://nikitabobko.github.io/AeroSpace/guide

i3 ライクな Window Manager

** Bat

better =cat=

*** Theme

- [catppuccin/bat: 🦇️ Soothing pastel theme for Bat](https://github.com/catppuccin/bat)

Theme には Catppuccin Frappe を使用しています。

初回のみキャッシュをリビルドしましょう。

#+begin_src
  bat cache --build
#+end_src

** DeskPad

- GitHub: https://github.com/Stengo/DeskPad

画面共有用に仮想ディスプレイ (Virtual Display) を作るアプリ

** Emacs

#+begin_src emacs-lisp
(emacs-version)
#+end_src

#+RESULTS:
: GNU Emacs 31.0.50 (build 1, aarch64-apple-darwin23.6.0, NS appkit-2487.70 Version 14.6.1 (Build 23G93))
:  of 2024-08-09

see https://github.com/ataka/emacs-d.git

** Eza

Better =ls=

#+begin_src
  brew install eza
#+end_src

** Fontforge

フォントを編集するアプリ。

ARM 用のアプリは提供されていない?
`brew` でインストールすると、次の警告が出ます。

#+begin_src
  ==> Caveats
  fontforge is built for Intel macOS and so requires Rosetta 2 to be installed.
  You can install Rosetta 2 with:
    softwareupdate --install-rosetta --agree-to-license
  Note that it is very difficult to remove Rosetta 2 once it is installed.
#+end_src

幸い手元の環境は既に Rosetta 2 だったのでそのままスルーします。

** fzf

=zoxide= との連携で力を発揮する Fazzy Finder

#+begin_src
  brew install fzf
#+end_src

** Git

- =.gitconfig=

** JankyBorders

- https://github.com/FelixKratz/JankyBorders

ウィンドウ枠に色を付けるツール。

コマンド名は =borders=

** Karabiner Elements

*** Dvorak Layout

#+begin_src
  '   ,   .   p   y      f   g   c   r   l
  a   o   e   u   u      d   h   t   n   s
  ;   q   j   k   x      b   m   w   v   ]
#+end_src

*** Home Row Mods

Home Row Mods の設定は https://github.com/Leo-keeb/Karabiner-Elements-Advanced-Settings を参考にしました。

#+begin_src
  '   ,   .   p   y      f   g   c   r   l
  Cmd Sft Opt Ctl i      d   Ctl Opt Sft Cmd
  ;   q   j   k   x      b   m   w   v   ]
#+end_src

** GNU Screen

- =.screenrc=

** oh my posh

*** oh my posh のインストール

#+begin_src
  brew install jandedobbeleer/oh-my-posh/oh-my-posh
#+end_src

** WezTerm

*** WezTerm のインストール

#+begin_src
  brew install --cask wezterm
#+end_src

*** WezTerm の使い方

- =Cmd + T= タブを新しく作る
- =Cmd + W= タブを閉じる

*** Theme

Catppuccin Frappe テーマを使用しています。

Wezterm はシステムのライト/ダークテーマの切替に対応していますが、その機能を利用していません。
Wezterm 上で使う CUI ツールが対応していないためです。

** zoxide

Better =cd=

#+begin_src
  brew install zoxide
#+end_src

** zsh

- =.zshrc=
- =.zprofile=

*** zsh (homebrew 版)

#+begin_src
  brew install zsh
#+end_src

**** zsh (homebrew 版) の設定

=/etc/shells= に次の行を追加します。

#+begin_src
  /opt/homebrew/bin/zsh
#+end_src

その後、ログイン・シェルの変更を実施します。

#+begin_src
  chsh -s /opt/homebrew/bin/zsh
#+end_src

* プログラミング言語の設定

** Mermaid

*** mmdc

Mermaid のソースコードから画像等を作成するコマンドラインツール。

**** mmdc のインストール

#+begin_src 
npm install -g @mermaid-js/mermaid-cli
#+end_src

**** Rakefile のサンプル

次の Rakefile を用意しておくと、ビルドが楽になります。

#+begin_src ruby
  PLANTUML = "/opt/homebrew/bin/plantuml"

  task :default => :uml

  desc "UML 図を更新する"
  task :uml => %w[
    foo.png
  ]

  rule '.png' => '.mmdc' do |t|
    sh "mmdc -i #{t.source} -o #{t.name}"
  end
#+end_src

** PlantUML

*** plantuml

PlantUML のソースコードから画像等を作成するコマンドラインツール。

**** plantuml のインストール

#+begin_src 
brew install plantuml
#+end_src

**** Rakefile のサンプル

次の Rakefile を用意しておくと、ビルドが楽になります。

#+begin_src ruby
  PLANTUML = "/opt/homebrew/bin/plantuml"

  task :default => :uml

  desc "UML 図を更新する"
  task :uml => %w[
    foo.png
  ]

  rule '.png' => '.plantuml' do |t|
    sh "#{PLANTUML} #{t.source}"
  end
#+end_src

* フォントの設定

** UDEV Gothic

- https://github.com/yuru7/udev-gothic

BIZ UDGothic と JetBrains Mono を組み合わせたフォント。

JetBrains Mono は Ligature に対応しています。

Nerd Fonts に対応した =UDEVGothic_NF_v2.0.0.zip= をダウンロードしています。

** Victor Mono

- https://rubjo.github.io/victor-mono/

Ligature に対応した英文フォント。

* Theme

** ANSI Escape Sequences

- Text Attributes
  - 0 : All attributes off
  - 1 : Bold on
  - 2 : Dim/Faint on
  - 3 : Italic on
  - 4 : Underscore
  - 5 : Blink on
  - 6 : Hidden on
  - 7 : Reverse video on
  - 8 : Concealed on
  - 9 : Strikethrough on

| Color Name     | Foreground Color | Background Color |
|----------------+------------------+------------------|
| Black          | 30               | 40               |
| Red            | 31               | 41               |
| Green          | 32               | 42               |
| Yellow         | 33               | 43               |
| Blue           | 34               | 44               |
| Magenta        | 35               | 45               |
| Cyan           | 36               | 46               |
| White          | 37               | 47               |
| Bright Black   | 90               | 100              |
| Bright Red     | 91               | 101              |
| Bright Green   | 92               | 102              |
| Bright Yellow  | 99               | 109              |
| Bright Blue    | 94               | 104              |
| Bright Magenta | 95               | 105              |
| Bright Cyan    | 96               | 106              |
| Bright White   | 97               | 107              |

** Catppuccine

*** Frappe

| Color Name | ANSI    | Bright  | ANSI Name | Bright Name |
|------------+---------+---------+-----------+-------------+
| Black      | #51576d | #626880 | surface1  | surface2    |
| Red        | #e78284 | #e78284 | red       | red         |
| Green      | #a6d189 | #a6d189 | green     | green       |
| Yellow     | #e5c890 | #e5c890 | yellow    | yellow      |
| Blue       | #8caaee | #8caaee | blue      | blue        |
| Magenta    | #f4b8e4 | #f4b8e4 | pink      | pink        |
| Cyan       | #81c8be | #81c8be | teal      | teal        |
| White      | #b5bfe2 | #a5adce | subtext1  | subtext0    |
