#!/usr/bin/env bash

# Colors taken from tokyonight theme (supported format: 0xAARRGGBB)
red="0xfff7768e"
blue="0xff7aa2f7"

options=(
	active_color="$red"
	inactive_color="$blue"
	hidpi=on # If set to on, the border will be drawn with retina resolution
	style=round
	width=10.0
)

borders "${options[@]}"
